### ISSUE TITLE
Code details for discussion

### ISSUE THREAD

**Issue by melodb** [openghg/fluxie#40]
Potential changes in the code:

- Change strings 'YS' and 'QS-DEC' in the notebook to 'year' and 'season' to make it more user friendly.
- What's the goal of "with io.capture_output() as captured"? Should the error messages be printed somewhere else? Is the verbose flag dispensable?
- In read_flux_total_fgases, we carry the standard deviation computed from both the lower and upper prior/posterior. In theory we could use only the lower or upper values to compute the std. I guess the current implementation is more general? Or should we simplify the code?
- Should we delete the function set_model_colors (first version)? Or is someone using it?
- Should we input to slice_flux the whole dict and delete the for-loop from the notebook cell? The function seems to be ready for a dictionary with multiple entries.
- Should we move the correction to set lower prior/posterior = 0 when it is <0  inside extract_region_flux? It is currently in read_flux_total_fgases.

**Comment by mo-aliceramsden** [comment]
Thanks for these suggestions, they all look great. These are my comments to add:

- Change strings 'YS' and 'QS-DEC' in the notebook to 'year' and 'season' to make it more user friendly. - _great idea_

- What's the goal of "with io.capture_output() as captured"? Should the error messages be printed somewhere else? Is the verbose flag dispensable? - _I originally put that line in to supress some of the print out related to reading in of files (as this was printing a lot of extra info for the total hfcs). Your 'verbose' flag is a much better way of doing this though, so that line could be removed now._

- In read_flux_total_fgases, we carry the standard deviation computed from both the lower and upper prior/posterior. In theory we could use only the lower or upper values to compute the std. I guess the current implementation is more general? Or should we simplify the code? - _I kept this more general so (if we ever wanted to) we could look at the individual standard deviations directly using the output of 'read_flux_total_fgases' but it seems unlikely that we'll ever want to do this?_

- Should we delete the function set_model_colors (first version)? Or is someone using it? - _Don't think there's any plans to use this old version any more, so feel free to delete._

- Should we input to slice_flux the whole dict and delete the for-loop from the notebook cell? The function seems to be ready for a dictionary with multiple entries. - _I put that extra for loop in because it seemed to reduce the amount of times that the kernel crashed (this was an issue we were having at the met office) but now we are using the icos-hosted version of the notebook, this is not an issue any more, so we can delete the for loop._

- Should we move the correction to set lower prior/posterior = 0 when it is <0 inside extract_region_flux? It is currently in read_flux_total_fgases. - _good idea_

**Comment by melodb** [comment]
Following Alice's feedback, I will do the following:
- Change strings 'YS' and 'QS-DEC' in the notebook to 'year' and 'season'
- Move the correction to set lower prior/posterior = 0 when it is <0 inside extract_region_flux

Regarding "with io.capture_output() as captured", I just realized that it is avoiding the prints from slice_flux (which do not have a verbose flag) so it is nice to have it there.
Regarding the other 3 points, I did not touch them as they might still be useful.

**Comment by alexdanjou** [comment]
Sorry, answering that quite late. 

Agree on deleting _set_model_colors_ (I think I created it and don't use it anymore, don't think anyone does). 
I think you're other suggestions are good!

**Comment by melodb** [comment]
I have deleted _set_model_colors_. I will close this issue now.
